// ignore_for_file: constant_identifier_names

enum PrinterMethod {
  getPlatformVersion,
  checkConnect,
  disconnect,
  connect_lan,
  connect_bt,
  connect_usb,
  set_auto_request_usb_permission,
  set_hold_usb_permission_queue,
  release_usb_permission_queue,
  get_usb_printers_needing_permission,
  request_usb_permissions,
  scan_bt,
  stop_scan_bt,
  get_bluetooth_devices,
  print_label,
  print_image,
  print_image_esc,
  bluetooth_enabled,
  request_bluetooth_enable,
  print_text,
  print_text_esc,
  print_barcode,
  print_qrcode,
  print_barcode_esc,
  print_qrcode_esc,
  check_printer_status,
  auto_connect_built_in,
  has_built_in_printer,
  get_built_in_printer_paper_size,
  send_raw_bytes,
  open_drawer;
}
